#!/bin/sh
if [ -e "/sys/class/power_supply/A*/online" ]; then
	status=$(cat /sys/class/power_supply/A*/online)
	case ${status} in
		1) profile="adp";;
		0) profile="bat";;
	esac
fi
echo "${profile:-adp}"
# vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
