#!/bin/sh

vgp=/sys/kernel/debug/vgaswitcheroo/switch
if [  ! -e ${vgp} ]; then
	grep -q i915    /proc/modules || modprobe i915
	grep -q radeon  /proc/modules || modprobe radeon
	grep -q nouveau /proc/modules || modprobe nouveau
fi

vga=$(grep + ${vgp})
pci=$(sed -nre 's/^[0-9].*\+.*[a-zA-Z]:([0-9].*$)/\1/p' ${vgp})
if [ -d /sys/bus/pci/drivers/nouveau/${pci} ];then
	drv=nouveau
elif [ -d /sys/bus/pci/drivers/radeon/${pci} ]; then
	drv=radeon
fi

case ${vga} in
	*:IGD:+*) echo "intel" ; exit;;
	*:DIS:+*) echo "${drv}"; exit;;
esac

drv="$(lspci -k | sed -nre 's/Kernel driver in use: ((i915|fglrx|radeon|nouveau|nvidia))/\1/p')"

echo "${drv:-invalid}"

# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
