#!/bin/sh
if [ -e /sys/kernel/debug/vgaswitcheroo/switch ]; then
	case ${1} in
		intel|radeon|nouveau) echo ON >/sys/kernel/debug/vgaswitcheroo/switch;;
	esac
fi
echo "Finished Stopping profile ${1} and moving back xorg.conf"
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
