#!/bin/sh
# $Id: $HOME/.script/ffp-pack,v 1.1 2011/11/15 -tclover Exp $
# a little script to put firefox profile to tmpfs
#
FFH="$HOME/.mozilla/firefox"
die() {  echo "* $@"; exit 1; }
CDIR="$PWD"
PF=$(basename "$FFH"/*.default)
[[ -z $PF ]] && die "profile is empty."
if [[ -z $(mount -t tmpfs | grep -F $FFH/$PF) ]]; then
	sudo mount ffp-$UID "$FFH"/$PF -t tmpfs -o user,exec,uid=$UID,gid=$GID,size=96m || \
	die "failed to mount ff-p-$UID tmpfs"
fi
cd "$FFH"
if [[ -f "$PF/.unpacked" ]]; then
	tar --exclude $PF/.unpacked -czpf $PF.tmp.tgz $PF || die "failed to pack the profie."
	mv $PF.tgz $PF.old.tgz || die "failed to override .old profile."
	mv $PF.tmp.tgz $PF.tgz || die "failed to move the profile."
else 
	{ tar xzpf $PF.tgz || tar xzpf $PF.old.tgz
	} && touch $PF/.unpacked || echo "failed to unpack the profile."
fi
cd "$CDIR"
unset CDIR PF FFH
#
# vim:fenc=utf-8:ci:pi:sts=0:sw=3:ts=3:
