#!/bin/sh
# $Id: ~/.scripts/fhp,v 2.0 2013/04/27 09:45:10 -tclover Exp $
# a script to put firefox profile to tmpfs, the following line should be put in 
# ~/.*shrc or ~/.*profile: `export FHP=$(ls -d ~/.mozilla/firefox/*.default)'
# and something like... in a crontab job: */30 * * * * $USER ~/.scripts/fhp.bash
die() {
	local _ret=$?
	echo "* $@"
	exit $_ret
}
[[ -z $FHP ]] && die "FHP profile env string is empty."
[[ -z $(sudo mount -t tmpfs | grep -F $FHP) ]] &&
	if [[ "$1" = "-z" ]]; then
			mount -t ext4 -o acl,user_xattr /dev/zram3 "$FHP" || die
			chmod $UID:$GID -R $FHP
		else
			sudo mount fhp "$FHP" -t tmpfs -o nodev,noexec,uid=$UID,gid=$GID,size=128m ||
			die "failed to mount fhp"
	fi
cd "${FHP%/*}"
if [[ -f "$FHP"/.unpacked ]]; then
	tar --exclude $FHP/.unpacked -czpf ${FHP##*/}.tmp.tgz ${FHP##*/}/ ||
		die "failed to pack the profie."
	mv ${FHP##*/}.tgz ${FHP##*/}.old.tgz || die "failed to override .old profile."
	mv ${FHP##*/}.tmp.tgz ${FHP##*/}.tgz || die "failed to move the profile."
else tar xpf ${FHP##*/}.tgz &>/dev/null || tar xpf ${FHP##*/}.old.tgz &>/dev/null 
	[[ $? ]] && touch "$FHP"/.unpacked || echo "failed to unpack the tarball."; fi
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=2:ts=2:
