#!/bin/sh
# $Id: ~/.scripts/iru, 2012/05/03 -tclover Exp $
for iface in eth0 wlan0 $@; do
	ipv4=$(ifconfig $iface | grep 'inet ' | head -n1 | awk '{ print $2 }')
	if [ -n "$ipv4" ]; then 
		~/.scripts/ipr -e$iface && /etc/init.d/iptables restart
		~/.scripts/ipb.zsh && /etc/init.d/ipset restart
	fi
	unset ipv4
done
# vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
