#!/bin/sh
for i in $(seq ${2:-16} ${3:-32}); do
  case $1 in
   -d|--del)
	   rm -f /dev/loop$i
	   ;;
   -a|--add|*)
	   [ -f /dev/lopp$i ] || {
	   	   mknod -m0660 /dev/loop$i b 7 $i 
	   	   chown root:disk /dev/loop$i
	   }
	   ;;
  esac
done
