#!/bin/sh
# $Id: $HOME/.scripts/xtr,v 2014/07/01 22:00:26 -tclover Exp $

# @SCRIPT: xtr
# @DESCRIPTION: eXTRact archives or tarball archives
# @USAGE: <file> <file> <...>

for file in "$@"; do
  case "$file" in
    *.tbz2*|*.tar.bz2*) CMP="tar -xvjf";;
    *.txz*|*.tar.xz*) CMP="tar -xvJf";;
    *.tgz"|*.tar.gz") CMP="tar -xvzf";;
    *.tar|*.cbt) CMP="tar -xvf";;
    *.zip|*.cbz) CMP=unzip;;
    *.rar|*.cbr) CMP="unrar x";;
    *.arj) CMP=unarj;;
    *.ace) CMP="unace x";;
    *.bz2) CMP=bunzip2;;
    *.xz) CMP=unxz;;
    *.gz) CMP=gunzip;;
    *.7z) CMP="7z x";;
    *.Z) CMP=uncompress;;
    *.gpg) GPG=gpg2;;
    *) echo "Error: failed to extract $file";;
  esac
done

if [ -n "$GPG" ]; then
  $GPG -d "$file" | $CMP -
else
  $CMP "$file"
fi

unset CMP GPG file

# vim:fenc=utf-8:ft=zsh:ci:pi:sts=0:sw=2:ts=2:
